// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: schedules.proto

package schedule_service

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ScheduleServiceClient is the client API for ScheduleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScheduleServiceClient interface {
	Create(ctx context.Context, in *CreateSchedule, opts ...grpc.CallOption) (*GetSchedule, error)
	GetByID(ctx context.Context, in *SchedulePrimaryKey, opts ...grpc.CallOption) (*GetSchedule, error)
	GetList(ctx context.Context, in *GetListScheduleRequest, opts ...grpc.CallOption) (*GetListScheduleResponse, error)
	Update(ctx context.Context, in *UpdateSchedule, opts ...grpc.CallOption) (*GetSchedule, error)
	Delete(ctx context.Context, in *SchedulePrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error)
	GetStudentSchedule(ctx context.Context, in *SchedulePrimaryKey, opts ...grpc.CallOption) (*GetStudentSchedules, error)
	GetForWeek(ctx context.Context, in *GetWeekScheduleRequest, opts ...grpc.CallOption) (*GetWeekScheduleResponse, error)
}

type scheduleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScheduleServiceClient(cc grpc.ClientConnInterface) ScheduleServiceClient {
	return &scheduleServiceClient{cc}
}

func (c *scheduleServiceClient) Create(ctx context.Context, in *CreateSchedule, opts ...grpc.CallOption) (*GetSchedule, error) {
	out := new(GetSchedule)
	err := c.cc.Invoke(ctx, "/schedule_service_go.ScheduleService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) GetByID(ctx context.Context, in *SchedulePrimaryKey, opts ...grpc.CallOption) (*GetSchedule, error) {
	out := new(GetSchedule)
	err := c.cc.Invoke(ctx, "/schedule_service_go.ScheduleService/GetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) GetList(ctx context.Context, in *GetListScheduleRequest, opts ...grpc.CallOption) (*GetListScheduleResponse, error) {
	out := new(GetListScheduleResponse)
	err := c.cc.Invoke(ctx, "/schedule_service_go.ScheduleService/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) Update(ctx context.Context, in *UpdateSchedule, opts ...grpc.CallOption) (*GetSchedule, error) {
	out := new(GetSchedule)
	err := c.cc.Invoke(ctx, "/schedule_service_go.ScheduleService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) Delete(ctx context.Context, in *SchedulePrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/schedule_service_go.ScheduleService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) GetStudentSchedule(ctx context.Context, in *SchedulePrimaryKey, opts ...grpc.CallOption) (*GetStudentSchedules, error) {
	out := new(GetStudentSchedules)
	err := c.cc.Invoke(ctx, "/schedule_service_go.ScheduleService/GetStudentSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) GetForWeek(ctx context.Context, in *GetWeekScheduleRequest, opts ...grpc.CallOption) (*GetWeekScheduleResponse, error) {
	out := new(GetWeekScheduleResponse)
	err := c.cc.Invoke(ctx, "/schedule_service_go.ScheduleService/GetForWeek", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScheduleServiceServer is the server API for ScheduleService service.
// All implementations should embed UnimplementedScheduleServiceServer
// for forward compatibility
type ScheduleServiceServer interface {
	Create(context.Context, *CreateSchedule) (*GetSchedule, error)
	GetByID(context.Context, *SchedulePrimaryKey) (*GetSchedule, error)
	GetList(context.Context, *GetListScheduleRequest) (*GetListScheduleResponse, error)
	Update(context.Context, *UpdateSchedule) (*GetSchedule, error)
	Delete(context.Context, *SchedulePrimaryKey) (*empty.Empty, error)
	GetStudentSchedule(context.Context, *SchedulePrimaryKey) (*GetStudentSchedules, error)
	GetForWeek(context.Context, *GetWeekScheduleRequest) (*GetWeekScheduleResponse, error)
}

// UnimplementedScheduleServiceServer should be embedded to have forward compatible implementations.
type UnimplementedScheduleServiceServer struct {
}

func (UnimplementedScheduleServiceServer) Create(context.Context, *CreateSchedule) (*GetSchedule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedScheduleServiceServer) GetByID(context.Context, *SchedulePrimaryKey) (*GetSchedule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedScheduleServiceServer) GetList(context.Context, *GetListScheduleRequest) (*GetListScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedScheduleServiceServer) Update(context.Context, *UpdateSchedule) (*GetSchedule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedScheduleServiceServer) Delete(context.Context, *SchedulePrimaryKey) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedScheduleServiceServer) GetStudentSchedule(context.Context, *SchedulePrimaryKey) (*GetStudentSchedules, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentSchedule not implemented")
}
func (UnimplementedScheduleServiceServer) GetForWeek(context.Context, *GetWeekScheduleRequest) (*GetWeekScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetForWeek not implemented")
}

// UnsafeScheduleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScheduleServiceServer will
// result in compilation errors.
type UnsafeScheduleServiceServer interface {
	mustEmbedUnimplementedScheduleServiceServer()
}

func RegisterScheduleServiceServer(s grpc.ServiceRegistrar, srv ScheduleServiceServer) {
	s.RegisterService(&ScheduleService_ServiceDesc, srv)
}

func _ScheduleService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSchedule)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedule_service_go.ScheduleService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).Create(ctx, req.(*CreateSchedule))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulePrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedule_service_go.ScheduleService/GetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetByID(ctx, req.(*SchedulePrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedule_service_go.ScheduleService/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetList(ctx, req.(*GetListScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSchedule)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedule_service_go.ScheduleService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).Update(ctx, req.(*UpdateSchedule))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulePrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedule_service_go.ScheduleService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).Delete(ctx, req.(*SchedulePrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_GetStudentSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulePrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetStudentSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedule_service_go.ScheduleService/GetStudentSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetStudentSchedule(ctx, req.(*SchedulePrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_GetForWeek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeekScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetForWeek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedule_service_go.ScheduleService/GetForWeek",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetForWeek(ctx, req.(*GetWeekScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScheduleService_ServiceDesc is the grpc.ServiceDesc for ScheduleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScheduleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schedule_service_go.ScheduleService",
	HandlerType: (*ScheduleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ScheduleService_Create_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _ScheduleService_GetByID_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _ScheduleService_GetList_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ScheduleService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ScheduleService_Delete_Handler,
		},
		{
			MethodName: "GetStudentSchedule",
			Handler:    _ScheduleService_GetStudentSchedule_Handler,
		},
		{
			MethodName: "GetForWeek",
			Handler:    _ScheduleService_GetForWeek_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schedules.proto",
}
