// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: managers.proto

package manager_service

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ManagerServiceClient is the client API for ManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManagerServiceClient interface {
	Create(ctx context.Context, in *CreateManager, opts ...grpc.CallOption) (*GetManager, error)
	GetByID(ctx context.Context, in *ManagerPrimaryKey, opts ...grpc.CallOption) (*GetManager, error)
	GetList(ctx context.Context, in *GetListManagerRequest, opts ...grpc.CallOption) (*GetListManagerResponse, error)
	Update(ctx context.Context, in *UpdateManager, opts ...grpc.CallOption) (*GetManager, error)
	Delete(ctx context.Context, in *ManagerPrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error)
	Login(ctx context.Context, in *ManagerLoginRequest, opts ...grpc.CallOption) (*ManagerLoginResponse, error)
	Register(ctx context.Context, in *ManagerRegisterRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	RegisterConfirm(ctx context.Context, in *ManagerRegisterConfRequest, opts ...grpc.CallOption) (*ManagerLoginResponse, error)
	ChangePassword(ctx context.Context, in *ManagerChangePassword, opts ...grpc.CallOption) (*ManagerChangePasswordResp, error)
}

type managerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManagerServiceClient(cc grpc.ClientConnInterface) ManagerServiceClient {
	return &managerServiceClient{cc}
}

func (c *managerServiceClient) Create(ctx context.Context, in *CreateManager, opts ...grpc.CallOption) (*GetManager, error) {
	out := new(GetManager)
	err := c.cc.Invoke(ctx, "/manager_service_go.ManagerService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) GetByID(ctx context.Context, in *ManagerPrimaryKey, opts ...grpc.CallOption) (*GetManager, error) {
	out := new(GetManager)
	err := c.cc.Invoke(ctx, "/manager_service_go.ManagerService/GetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) GetList(ctx context.Context, in *GetListManagerRequest, opts ...grpc.CallOption) (*GetListManagerResponse, error) {
	out := new(GetListManagerResponse)
	err := c.cc.Invoke(ctx, "/manager_service_go.ManagerService/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) Update(ctx context.Context, in *UpdateManager, opts ...grpc.CallOption) (*GetManager, error) {
	out := new(GetManager)
	err := c.cc.Invoke(ctx, "/manager_service_go.ManagerService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) Delete(ctx context.Context, in *ManagerPrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/manager_service_go.ManagerService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) Login(ctx context.Context, in *ManagerLoginRequest, opts ...grpc.CallOption) (*ManagerLoginResponse, error) {
	out := new(ManagerLoginResponse)
	err := c.cc.Invoke(ctx, "/manager_service_go.ManagerService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) Register(ctx context.Context, in *ManagerRegisterRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/manager_service_go.ManagerService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) RegisterConfirm(ctx context.Context, in *ManagerRegisterConfRequest, opts ...grpc.CallOption) (*ManagerLoginResponse, error) {
	out := new(ManagerLoginResponse)
	err := c.cc.Invoke(ctx, "/manager_service_go.ManagerService/RegisterConfirm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) ChangePassword(ctx context.Context, in *ManagerChangePassword, opts ...grpc.CallOption) (*ManagerChangePasswordResp, error) {
	out := new(ManagerChangePasswordResp)
	err := c.cc.Invoke(ctx, "/manager_service_go.ManagerService/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerServiceServer is the server API for ManagerService service.
// All implementations should embed UnimplementedManagerServiceServer
// for forward compatibility
type ManagerServiceServer interface {
	Create(context.Context, *CreateManager) (*GetManager, error)
	GetByID(context.Context, *ManagerPrimaryKey) (*GetManager, error)
	GetList(context.Context, *GetListManagerRequest) (*GetListManagerResponse, error)
	Update(context.Context, *UpdateManager) (*GetManager, error)
	Delete(context.Context, *ManagerPrimaryKey) (*empty.Empty, error)
	Login(context.Context, *ManagerLoginRequest) (*ManagerLoginResponse, error)
	Register(context.Context, *ManagerRegisterRequest) (*empty.Empty, error)
	RegisterConfirm(context.Context, *ManagerRegisterConfRequest) (*ManagerLoginResponse, error)
	ChangePassword(context.Context, *ManagerChangePassword) (*ManagerChangePasswordResp, error)
}

// UnimplementedManagerServiceServer should be embedded to have forward compatible implementations.
type UnimplementedManagerServiceServer struct {
}

func (UnimplementedManagerServiceServer) Create(context.Context, *CreateManager) (*GetManager, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedManagerServiceServer) GetByID(context.Context, *ManagerPrimaryKey) (*GetManager, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedManagerServiceServer) GetList(context.Context, *GetListManagerRequest) (*GetListManagerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedManagerServiceServer) Update(context.Context, *UpdateManager) (*GetManager, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedManagerServiceServer) Delete(context.Context, *ManagerPrimaryKey) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedManagerServiceServer) Login(context.Context, *ManagerLoginRequest) (*ManagerLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedManagerServiceServer) Register(context.Context, *ManagerRegisterRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedManagerServiceServer) RegisterConfirm(context.Context, *ManagerRegisterConfRequest) (*ManagerLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterConfirm not implemented")
}
func (UnimplementedManagerServiceServer) ChangePassword(context.Context, *ManagerChangePassword) (*ManagerChangePasswordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}

// UnsafeManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagerServiceServer will
// result in compilation errors.
type UnsafeManagerServiceServer interface {
	mustEmbedUnimplementedManagerServiceServer()
}

func RegisterManagerServiceServer(s grpc.ServiceRegistrar, srv ManagerServiceServer) {
	s.RegisterService(&ManagerService_ServiceDesc, srv)
}

func _ManagerService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateManager)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_service_go.ManagerService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).Create(ctx, req.(*CreateManager))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagerPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_service_go.ManagerService/GetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).GetByID(ctx, req.(*ManagerPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListManagerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_service_go.ManagerService/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).GetList(ctx, req.(*GetListManagerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateManager)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_service_go.ManagerService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).Update(ctx, req.(*UpdateManager))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagerPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_service_go.ManagerService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).Delete(ctx, req.(*ManagerPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagerLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_service_go.ManagerService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).Login(ctx, req.(*ManagerLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagerRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_service_go.ManagerService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).Register(ctx, req.(*ManagerRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_RegisterConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagerRegisterConfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).RegisterConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_service_go.ManagerService/RegisterConfirm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).RegisterConfirm(ctx, req.(*ManagerRegisterConfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagerChangePassword)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_service_go.ManagerService/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).ChangePassword(ctx, req.(*ManagerChangePassword))
	}
	return interceptor(ctx, in, info, handler)
}

// ManagerService_ServiceDesc is the grpc.ServiceDesc for ManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "manager_service_go.ManagerService",
	HandlerType: (*ManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ManagerService_Create_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _ManagerService_GetByID_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _ManagerService_GetList_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ManagerService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ManagerService_Delete_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _ManagerService_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _ManagerService_Register_Handler,
		},
		{
			MethodName: "RegisterConfirm",
			Handler:    _ManagerService_RegisterConfirm_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _ManagerService_ChangePassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "managers.proto",
}
